### ISSUE TITLE
Any way to prevent USB Drives from "Spinning Down"?

### ISSUE THREAD

**Issue by davedoc1984** [danmons/retronas#17]
An issue I have come across which can cause some games to crash if run from the CIFS Shares is if the Hard Drive spins down due to inactivity, it can cause some games to crash because the Drive has to spin back up.

Anyway of preventing the "Spin Down" of the Drive?

**Comment by birdybro** [comment]
https://man7.org/linux/man-pages/man8/hdparm.8.html - hdparm would be the way to do this.

**Comment by danmons** [comment]
I can look at adding a startup service that runs hdparm with -B 254 (highest power, least likely spin down) followed by -B 255 (disable power management all together if available in the hardware) on all attached drives. 

You can test for yourself (run the commands as root/sudo), but that can definitely be thrown in to one of the menus as an option.

**Comment by davedoc1984** [comment]
HDPARM command not found?

**Comment by sairuk** [comment]
Have a go with `hdparm -S 0 /dev/sda1`

from the man page
"Put the drive into idle (low-power) mode, and also set the standby (spindown) timeout for the drive."
"A value of zero means "timeouts are disabled":  the device will not automatically enter standby mode."

**Comment by davedoc1984** [comment]
Gave that a try and the Drive does still spin down after some inactivity causing games to crash :(

I guess its the Drives firmware that is telling it to spin down and thus we can't control it in software?

**Comment by sairuk** [comment]
If you run `hdparm -I /dev/sda` check the your drive says it has `Power Manager feature set enabled` and then confirm the `Advanced power management level` before and after the commands, also this wont persist over reboots without further configuration

Another option may be to look at drive Acoustic levels it may be supported on your drive (it is not on my local usb) with `hdparm -M /dev/sda`

What is the disk model? Looking at the arch [hdparm wiki](https://wiki.archlinux.org/title/Hdparm#Putting_a_drive_to_sleep_directly_after_boot) WD Green drives are problematic with hdparm.

Otherwise a incredibly hacky option could be to touch a file or read a block every so often with cron or a systemd timer.

**Comment by sairuk** [comment]
Had a look at a USB drive i chucked onto my Pi, can you confirm the settings are taken by your drive? Mine will not support a status with `hdparm -C /dev/sda` unfortunately but I can confirm APM is disabled after the setting `hdparm -B 255 /dev/sda` is applied.

```
root@raspberrypi:~# hdparm -C /dev/sda

/dev/sda:
SG_IO: bad/missing sense data, sb[]:  70 00 01 00 00 00 00 0a 00 00 00 00 00 1d 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 drive state is:  unknown
root@raspberrypi:~# 
```

```
ATA device, with non-removable media
  Model Number:       WDC WD3200BEVT-22ZCT0    
  Serial Number:      WD-WXE408KJ2306
  Firmware Revision:  11.01A11
  Transport:          Serial, SATA 1.0a, SATA II Extensions, SATA Rev 2.5 
```

```
  Standby timer values: spec'd by Standard, with device specific minimum
  Advanced power management level: 128 
  Recommended acoustic management value: 128, current value: 254 
```

```
root@raspberrypi:~# hdparm -S 0 /dev/sda

/dev/sda:
 setting standby to 0 (off)
SG_IO: bad/missing sense data, sb[]:  70 00 01 00 00 00 00 0a 00 00 00 00 00 1d 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
root@raspberrypi:~# 
```

```
root@raspberrypi:~# hdparm -B 255 /dev/sda

/dev/sda:
 setting Advanced Power Management level to disabled
SG_IO: bad/missing sense data, sb[]:  70 00 01 00 00 00 00 0a 00 00 00 00 00 1d 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 APM_level	= off
root@raspberrypi:~#
```

```
	Advanced power management level: disabled
```

I was/am investigating the option of having hdparm read random sector from the hdd on a systemd timer to prevent sleep atm, something like this with a systemd timer so we can introduce some further timed randomness. I am open for comment on this approach though.

```
#!/bin/bash
#
# Prevent a disk going to sleep by reading a sector
#

# list the drives that need to be punished
NOSLEEP=(
  /dev/sda
)


# REQUIREMENTS
REQFAIL=0
[ ! -x /usr/sbin/hdparm ] && echo "hdparm not executable" && REQFAIL=1
[ ! -x /usr/bin/shuf ] && echo "shuf not executable" && REQFAIL=1
[ $REQFAIL -ne 0 ] && echo "Failed requiements, check previous messages" && exit $REQFAIL


for DISK in ${NOSLEEP[@]}
do
        MAXSECTOR=$(hdparm -I $DISK | awk '/LBA48/{print $5}')
        RANDSECTOR=$(shuf -i 1-${MAXSECTOR} -n 1)
        echo "Reading ${RANDSECTOR} (max:${MAXSECTOR}) from ${DISK}"
        hdparm --readsector $RANDSECTOR $DISK &>/dev/null
done
```

**Comment by sairuk** [comment]
I've added a branch with experimental hdparm support, @davedoc1984 can you please test it against your drive. 

Since none of the standard hdparm solutions have worked for you, its best we check it against your setup.

I have included the above script as a service that runs on a timer to _poke_ the drive at random, the scripts is currently hard coded to use /dev/sda while testing.

To switch to the new branch, please ssh into a RetronNAS device and do the following

```
# cd /opt/retronas
# git pull
# git checkout hdparm
# /opt/retronas/retronas.sh -g
```

Once retronas loads you should see an `Advanced Tools` menu, the hdparm menu is under this with the options discussed in this issue

To switch back to the main branch

```
# cd /opt/retronas
# git pull
# git checkout main
# /opt/retronas/retronas.sh
```

**Comment by davedoc1984** [comment]
Hi Dan, mine appears as \dev\sda1 does that make any difference?

![image](https://user-images.githubusercontent.com/97349996/153292101-165d3060-fd18-44a4-b2ca-b642f5451fc8.png)

**Comment by sairuk** [comment]
> Hi Dan, mine appears as /dev/sda1 does that make any difference?

The /dev/sda**1** signifies the first partition on the drive, this number increments when adding additional partitions on a drive. The partitions is what is mounted on the system with a filesystem applied (in most cases)

We are targeting disk functionality which is /dev/sda (no 1)

**Comment by davedoc1984** [comment]
![image](https://user-images.githubusercontent.com/97349996/153296515-77ba15ed-71cc-4979-90e6-1fcd7d391008.png)

**Comment by sairuk** [comment]
OK I will take a look thanks, that looks to have started happening here as well now.

**Comment by sairuk** [comment]
I've committed some fixes, oversights when moving from systemd instances to a static service in the code and some items i didn't catch working on a VM vs hardware, if you are still on the hdparm branch you can change into the directory and issue `git pull` to update your local copy.

You will then need to reinstall the hdparm instance using `Install` from the menu. A subsequent `Stop` and `Start` of the service should suffice to get it going as a Start will issue a reset-failed on the. 

If not please post the results of the `Query Status` output in full.

Thanks

**Comment by sairuk** [comment]
This is running OK for me with these fixes, so i'm going to merge in the fixes

![image](https://user-images.githubusercontent.com/526372/153520001-2499d275-47aa-4102-a5af-0c33343af38c.png)

**Comment by sairuk** [comment]
Merged to main branch in commit https://github.com/danmons/retronas/commit/e02460d278f940db171f9409bbd146f396e5bb38

**Comment by davedoc1984** [comment]
Its not fixed for me. I still have the issue with my Drive Spinning down. 

![image](https://user-images.githubusercontent.com/97349996/154984726-1ee1f42b-8ce9-4264-a601-7284899abd2c.png)

**Comment by tjanas** [comment]
> it can cause some games to crash because the Drive has to spin back up.

@davedoc1984 can you provide some game examples?
